# -*- coding: utf-8 -*-
"""log

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nw8wGvXKbnxi_6xnO3vb6jIJUiCQ5BjR
"""

import logging

def init_console_logger(logger, verbose=False):
    """
    Initializes Logging to the Console for a logger when it is called on it. Sets the level of the message to either Info or Debug (pos. 2 and 3 in hierarchy respectively)
    and defines the structure of the type of logger message the logger can produce.
    Args:
        logger:  Logger object
                 (Type: logging.Logger)
    Kwargs:
        verbose:  If true, prints verbose information to stdout. False by default.
                  (Type: bool)
    """
    # Log to stderr also
    #sets hierarchy level for log messages (If verbose, then level is pumped up to DEBUG)
    stream_handler = logging.StreamHandler()
    if verbose:
        stream_handler.setLevel(logging.DEBUG)
    else:
        stream_handler.setLevel(logging.INFO)
    
    #initializes format in which LogRecord is printed in the console
    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    stream_handler.setFormatter(formatter)
    
    #logger in question gets the defined logging functionalities
    logger.addHandler(stream_handler)